### ISSUE TITLE
Extension cannot be downloaded to makecode(microbit)

### ISSUE THREAD

**Issue by DoraLC** [designingourtomorrow/pxt-pulse#1]
I am not able to download the extension to makecode, message "request failed" occurred. However, there is no problem with the test version of the extension (https://github.com/designingourtomorrow/pxt-pulse-test).

**Comment by designingourtomorrow** [comment]
Terribly sorry about that.  The fault was a backslash in the wrong place in the .json, and it was fixed by a contributer.
